=== Bertley/Support-Ticket-/xml/supportticket.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tickets">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ticket" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="date" maxOccurs="1" type="xs:date"/>
                            <xs:element name="title" maxOccurs="1" type="xs:string"/>
                            <xs:element name="message" minOccurs="1">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="userId" type="xs:string" use="required"/>
                                            <xs:attribute name="datetime" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="response" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="userId" type="xs:string" use="required"/>
                                            <xs:attribute name="datetime" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="number" type="xs:integer" use="required" />
                        <xs:attribute name="client" type="xs:integer" use="required"/>
                        <xs:attribute name="status" type="status" use="required" />
                        <xs:attribute name="supportCat" type="category" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!--CUSTOM TYPE-->
    <xs:simpleType name="status">
        <xs:restriction base="xs:string">
            <xs:enumeration value="resolved"/>
            <xs:enumeration value="on-going"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="category">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Spam or Abuse"/>
            <xs:enumeration value="Something isn't Working"/>
            <xs:enumeration value="General Feedback"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Bertley/Support-Ticket-/xml/Supportticket1.xml
<?xml version="1.0" encoding="utf-8"?>
<tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="supportticket.xsd">
<ticket number="1522378312" status="resolved" supportCat="Something isn't Working" client="1"><date>2018-03-30</date><title>I love your website </title><message userId="1" datetime="2018-03-30 04:51:52">You have the best interface for this assignment! Good work, keep giving you best effort</message><response userId="2" datetime="2018-03-30 04:54:35">Thank you! </response></ticket><ticket number="1522378398" status="resolved" supportCat="Something isn't Working" client="3"><date>2018-03-30</date><title>My follow button isn't working </title><message userId="3" datetime="2018-03-30 04:53:18">Please can someone check that out, i can't seem to be able to follow anyone. &#13;
Thanks</message><response userId="2" datetime="2018-03-30 04:54:59">It's working now </response></ticket><ticket number="1522378743" status="resolved" supportCat="General Feedback" client="1"><date>2018-03-30</date><title>Hey </title><message userId="1" datetime="2018-03-30 04:59:03">Thanks for always being there </message><response userId="2" datetime="2018-03-30 05:08:45">you're welcome </response></ticket><ticket number="1522687242" status="resolved" supportCat="Spam or Abuse" client="3"><date>2018-04-02</date><title>Hey there </title><message userId="3" datetime="2018-04-02 18:40:42">window.onload = pageReady()</message><response userId="2" datetime="2018-04-02 18:41:40">vggvgvv</response><response userId="2" datetime="2018-04-02 18:41:40">vggvgvv</response></ticket></tickets>
